### ISSUE TITLE
servo duty cycle / frequency incorrect for our servos

### ISSUE THREAD

**Issue by explosivose** [explosivose/coderbot#4]
Rest point for servos is 1.5ms
Using 500Hz (2ms) and 100 range, the duty cycle goes from 55 (counter-clockwise) to 95 (clockwise) where 75 is the rest point 

`coderbot.py` needs to be updated to match this data to drive servos in the correct directions for all commands (forward, backward, left, right, etc )

**Comment by danentwistle** [comment]
issue has been resolved

Servo frequency should be 50Hz. 1ms pulse is one extreme, and 2ms is the other, 1.5ms is mid-point (rest). It's the same for continuous rotation servos and the arm 120deg micro servo
