### ISSUE TITLE
Custom Blocks

### ISSUE THREAD

**Issue by explosivose** [explosivose/coderbot#5]
I tried implementing custom blocks in `blocks.js` ( see https://github.com/explosivose/coderbot_lboro/commit/869b9aa2cf5ff66005bb5d62b12fbb9df931615f) But the blocks do not appear in the coderbot blockly program page. What did I miss?

**Comment by elsw** [comment]
There is quite a few things generated by build.py in the blockly folder, maybe some of these have to be rebuilt?

**Comment by danentwistle** [comment]
Issue was resolved ( the blocks needed to be added to XML files to appear in the library )

https://github.com/explosivose/coderbot_lboro/wiki/Blockly
