### ISSUE TITLE
Error: takePhoto() doesn't work when ./photos directory does not exist 

### ISSUE THREAD

**Issue by danentwistle** [explosivose/coderbot#6]
The ./photos directory should be created if it does not exist so that taking photos can work

Consider clearing the contents of this folder automatically on boot to avoid filling the disk

**Comment by explosivose** [comment]
https://github.com/explosivose/coderbot_lboro/commit/6635ed86e398b712747f1126b73e1f11606371e2

Added the ./photos directory to the repository so in future it should always be there to store images.
