### ISSUE TITLE
Robot names / unique IDs

### ISSUE THREAD

**Issue by danentwistle** [explosivose/coderbot#7]
When we deploy a number of robots it would be useful if they could be differentiated with unique names. This name would be displayed as unique SSIDs or registered as a unique name on a separate webserver that displays robots and acts as a gateway to authenticate users...

I imagine their unique name is set as a variable in coderbot.py and is also configurable as a setting in config.py & coderbot.cfg ?

**Comment by elsw** [comment]
Currently the Pis will be numbered and can be accessed by hotspot named Lboro Coderbot XX or locally at 192.168.0.1XX, where XX is the number.
